name: CI Test

on:
  push:
    branches:
    - main
    paths:
    - project/**
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install pandas
      run: |
        python -m pip install pandas
      
    # Run test.sh
    - name: Project Test
      run: |
        cd project  
        chmod +x tests.sh
        ./tests.sh
