name: CI Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    # Install dependencies
    - name: Install dependencies
      run: |
        cd project
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Eğer requirements.txt dosyanız varsa

      
      
    # Run test.sh
    - name: Project Test
      run: |
        cd project  
        ./tests.sh
