name: CI Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Print GITHUB_WORKSPACE
      run: echo ${GITHUB_WORKSPACE}
      working-directory: $GITHUB_WORKSPACE/tmp
      
    # Run test.sh
    - name: Project Test
      run: |
        ./project/tests.sh
